#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: My_IAM
  version: alpha
  namespace: thor
  tags:
    - IAM
spec:
  enabled: true
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: 'registered'
      httpBasicAuth:
        applicationLookup: 'registered'