#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Log
apiVersion: api.webmethods.io/beta
metadata:
  name: log_invocation
  version: alpha
  namespace: thor
  tags:
    - log_invocation
spec:
  enabled: true
  logRequestHeaders: true # default value = false
  logResponseHeaders: true # default value = false
  logRequestPayload: true # default value = false
  logResponsePayload: true # default value = false
  compressPayloads: true # default value = false
  logGenerationFrequency: always
  destination:
    - self
    - dev_portals:
      - devportal1 #name of the portal instance in the gateway
    - email:
      - daso@ibm.com
      - daso@sag.com
      - daso@sag.com    