kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: api
  namespace: Edit_test
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: api-spec.yml
  policy-sequence:
    - $ref: dev:MyPol:1.0
