#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySeq
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq
  version: 1
  namespace: thor
  tags:
    - seq
spec:
  transport:
    - $ref: thor:transport:alpha
  iam:
    - $ref: thor:My_IAM:alpha
  monitoring:
    - $ref: thor:log_invocation:alpha
  routing:
    - $ref: thor:routing:alpha
  req-processing:
    - $ref: thor:validate_API_Specification_policy:alpha
    - $ref: thor:request_processing_policy:alpha
  res-processing:
    - $ref: thor:response_processing_policy:alpha
