#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Endpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: endpoint
  version: alpha
  namespace: thor
spec:
  url: http://petstore.swagger.io
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
