#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: routing
  version: alpha
  namespace: thor
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: daso:endpoint:alpha